version: '2'

services:
  
  deathrecordpuller:
    build: ./DeathRecord_Puller/.
    restart: always
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      env_file: .env.production
      
  gt-fhir2:
    build:
      context: ./GT-FHIR2/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8181:8080"