version: '2'

services:
  
  deathrecordpuller:
    build: ./DeathRecord_Puller/.
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      env_file: .env.production
