/*
 * EDRS Submission API
 * This is the swagger documentation for DeathDataHub's EDRS Submission API. This API's purpose is to allow Medical Examiners and coroners to submit a signed IngestDeathRecord to a remote Electronic Death Record System. Although this is part of the deathdatahub main platform, the parameters are complex enough to warrent it's own swagger doc file
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Michael.Riley@gtri.gatech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gatech.edu.DeathRecordPuller.EDRS.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * IngestDeathRecord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-09T17:25:26.415Z")
public class IngestDeathRecord {
	@SerializedName("Decedent")
	private IngestDecedent decedent = null;

	@SerializedName("Certifier")
	private IngestCertifier certifier = null;

	@SerializedName("Contents")
	private IngestContents contents = null;

	public IngestDeathRecord decedent(IngestDecedent decedent) {
		this.decedent = decedent;
		return this;
	}

	/**
	 * Get decedent
	 * 
	 * @return decedent
	 **/

	public IngestDecedent getDecedent() {
		return decedent;
	}

	public void setDecedent(IngestDecedent decedent) {
		this.decedent = decedent;
	}

	public IngestDeathRecord certifier(IngestCertifier certifier) {
		this.certifier = certifier;
		return this;
	}

	/**
	 * Get certifier
	 * 
	 * @return certifier
	 **/

	public IngestCertifier getCertifier() {
		return certifier;
	}

	public void setCertifier(IngestCertifier certifier) {
		this.certifier = certifier;
	}

	public IngestDeathRecord contents(IngestContents contents) {
		this.contents = contents;
		return this;
	}

	/**
	 * Get contents
	 * 
	 * @return contents
	 **/

	public IngestContents getContents() {
		return contents;
	}

	public void setContents(IngestContents contents) {
		this.contents = contents;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		IngestDeathRecord ingestDeathRecord = (IngestDeathRecord) o;
		return Objects.equals(this.decedent, ingestDeathRecord.decedent)
				&& Objects.equals(this.certifier, ingestDeathRecord.certifier)
				&& Objects.equals(this.contents, ingestDeathRecord.contents);
	}

	@Override
	public int hashCode() {
		return Objects.hash(decedent, certifier, contents);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class IngestDeathRecord {\n");

		sb.append("    decedent: ").append(toIndentedString(decedent)).append("\n");
		sb.append("    certifier: ").append(toIndentedString(certifier)).append("\n");
		sb.append("    contents: ").append(toIndentedString(contents)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
