const identifiers = [
  'Patient__Admission_DateTime',
  'Patient__Birth_Date',
  'Patient__Date_Discharged',
  'Patient__Date_of_Onset',
  'Patient__Death_Date',
  'Patient__Diagnosis',
  'Patient__Ethnicity',
  'Patient__ID',
  'Patient__Immunization_History',
  'Patient__Insurance_Type',
  'Patient__Lab_Order_Code',
  'Patient__Lab_Tests_Performed',
  'Patient__Medication_Provided',
  'Patient__Name',
  'Patient__Occupation',
  'Patient__Parents_Guardians',
  'Patient__PatientClass',
  'Patient__Placer_Order_Code',
  'Patient__Preferred_Language',
  'Patient__Pregnant',
  'Patient__Race',
  'Patient__Sex',
  'Patient__Street_Address',
  'Patient__Symptoms',
  'Patient__Trigger_Code',
  'Patient__Visit_DateTime',
  'Patient__Travel_History'
]

export { identifiers };
